#!/bin/bash

input="$1"
ver="$2"
abi="$3"

version="$ver-$abi"

deps=", linux-source-${ver}"

for var in debian/control.d/vars.*; do
	flavour=$(basename $var | sed 's/.*\.//')
	. $var
	deps="${deps}, linux-headers-${version}-${flavour} [${arch}]"
done

cat $input | sed -e "s#HEADER_DEPS#${deps}#g"
